#VERSION = DEBUG
VERSION = RELEASE
ARCH  = 64

CUDA_INSTALL_PATH ?= /usr/local/cuda
CUDA_SDK_PATH     ?= $(HOME)/NVIDIA_GPU_Computing_SDK/C
CUDA_SDK_SHARED_PATH ?= $(HOME)/NVIDIA_GPU_Computing_SDK/shared
CPP = g++
CC = gcc
NVCC    = $(CUDA_INSTALL_PATH)/bin/nvcc -ccbin /usr/bin/
MAKE = make -j4


ifeq "$(ARCH)" "32"
	CUDA_LIBS += -lcutil -lcudart -lshrutil
	CUDA_LIB_DIRS += -L$(CUDA_INSTALL_PATH)/lib
else
	CUDA_LIBS += -lcudart -lcublas
	CUDA_LIB_DIRS += -L$(CUDA_INSTALL_PATH)/lib64
endif

ifeq "$(VERSION)" "DEBUG"
	DEFINES += -DDEBUGGING
	CFLAGS += -g -Wall -pg
    DEFINES      += -D_DEBUG
else # RELEASE
	CFLAGS = -O3 -ffast-math -fomit-frame-pointer -ftree-vectorize -DBRANCH_PREDICTION -mfpmath=sse
    DEFINES      += -D_NDEBUG
endif
    NVCC_FLAGS   = --compiler-options -fno-inline -use_fast_math 
#-arch=sm_52
#-lshrutil_x86_64 is for logging in 64 bits system... Change it to 32 bits as needed
#see the SDK/shared directory
CUDA_LIB_DIRS +=  -L$(CUDA_SDK_PATH)/lib -L/usr/local/lib -L$(CUDA_SDK_SHARED_PATH)/lib

CUDA_COMMON_DIR := $(CUDA_SDK_PATH)/common
CUDA_INCLUDES   := -I$(CUDA_INSTALL_PATH)/include -I$(CUDA_SDK_SHARED_PATH)/inc -I$(CUDA_COMMON_DIR)/inc -I/usr/lib/cuda/include -I$(CUDA_SDK_PATH)/common/inc

NVCC_FLAGS += $(CUDA_INCLUDES)
NVCC_FLAGS += $(CUDA_LIB_DIRS)
NVCC_FLAGS += $(CUDA_LIBS)


CFLAGS += -Wno-write-strings

DEFINES += -DLINUX -D_REENTRANT

# Enable SSE
#CFLAGS += -msse
DEFINES += -DENABLE_BENCHMARKING
